### ISSUE TITLE
Issue after including ruleset 

### ISSUE THREAD

**Issue by svenelele** [sonar-xsl/Sonar-XSL-Plugin#26]
Hello,

We are having issues with the XSL plugin. As soon as we build package with our ruleset we get below warning. I see that there is a existing issue open, however it does not seem to be trivial and just "Warning" because stylesheets are not properly scanned.

Sonarqube version 9.2.4 (build 50792), PostgreSQL 13.5

`Error on line 1 column 1 of jar:file:/home/<user>/.sonar/cache/e1a8926da7efa1faa8e6c20499cdfcc7/sonar-xsl-plugin.jar_unzip/META-INF/lib/sonar-schematron-reactor-1.0.0-SNAPSHOT.jar!/schematron-code/:
  SXXP0003: Error reported by XML parser: Premature end of file.
Warning at char 9 in xsl:value-of/@select on line 2221 column 96 of iso_schematron_skeleton_for_saxon.xsl:
  FODC0002: Document has been marked not available:
`

Also when activating the rule we are getting following stack message when scanning:
`ERROR: Error during SonarScanner execution
java.lang.ClassCastException: java.lang.String incompatible with java.lang.Boolean
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.reset(XMLEntityManager.java:1547)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.reset(XMLStreamReaderImpl.java:284)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.init(XMLStreamReaderImpl.java:260)
`

**Comment by jimetevenard** [comment]
Hi @svenelele,

> As soon as we build package with our ruleset we get below warning. I see that there is a existing issue open, however it does not seem to be trivial and just "Warning" because stylesheets are not properly scanned.

Do you still have these troubles with [Release 1.0.0-RC1 · sonar-xsl/Sonar-XSL-Plugin](https://github.com/sonar-xsl/Sonar-XSL-Plugin/releases/tag/v1.0.0-RC1) ?
This release was meant to fix #7 and #5.

> Also when activating the rule we are getting following stack message when scanning:
> ERROR: Error during SonarScanner execution java.lang.ClassCastException: java.lang.String incompatible with java.lang.Boolean at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.reset(XMLEntityManager.java:1547) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.reset(XMLStreamReaderImpl.java:284) at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.init(XMLStreamReaderImpl.java:260) 

Could you provide the full (or, at least, a longer excerpt) _stacktrace_ ?  
I can't see the _root cause_ of your problem since your excerpt only mentions java.xml.* classes.

Regards,
Jim.
