### ISSUE TITLE
ERROR: Error during SonarScanner execution java.lang.ClassCastException

### ISSUE THREAD

**Issue by gatt** [sonar-xsl/Sonar-XSL-Plugin#30]
Hi

When trying to analyze xsl files with the current sonar scanner (4.7.0.2747) the following exception occurs:

`
ERROR: Error during SonarScanner execution
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.reset(XMLEntityManager.java:1547)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.reset(XMLStreamReaderImpl.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.init(XMLStreamReaderImpl.java:260)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:208)
	at java.xml/com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(XMLInputFactoryImpl.java:262)
	at java.xml/com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:134)
	at org.sonar.plugins.xml.highlighting.XMLHighlighting.highlightXML(XMLHighlighting.java:87)
	at org.sonar.plugins.xml.highlighting.XMLHighlighting.<init>(XMLHighlighting.java:71)
	at org.sonar.plugins.xml.highlighting.XMLHighlighting.<init>(XMLHighlighting.java:50)
	at org.sonarxsl.schematron.SchematronSensor.execute(SchematronSensor.java:103)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:81)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:396)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:392)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:361)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
`

I've tried it with different xslt files on Windows and Linux using the bundled OpenJDK 11.0.14.1 from Sonar-Scanner.
Do you have any hints what i can do?
Greetings

**Comment by jimetevenard** [comment]
Hi, I did not manage to reproduce this with the versions below : 

- Could you please provinde the version of SonarQube you're using ?
- The class `org.apache.xerces.internal.impl.XMLEntityManager` seems to be involed in the stacktrace, do you have XML Entities in your XSLT files ?
- Is it possible for to join a exemple of these files ? (or email it to `contact@jimetevenard.com`) ?

<details>
  <summary>Version I used today (I did not reproduce)</summary>

### Sonar-XSL-Plugin : v1.0.0-RC1

[Sonar-XSL-Plugin v1.0.0-RC1](https://github.com/sonar-xsl/Sonar-XSL-Plugin/releases/tag/v1.0.0-RC1)

 <h3>SonarScanner : 4.8.0.2856</h3>
 <pre><code>docker run -it sonarsource/sonar-scanner-cli sonar-scanner --version       
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: <strong>SonarScanner 4.8.0.2856</strong>
INFO: Java 11.0.18 Alpine (64-bit)
INFO: Linux 5.15.49-linuxkit amd64</code></pre>

  <h3>SonarQube : 9.9 CE</h3>
  <pre><code>Community Edition Version 9.9 (build 65466)</code></pre>



</details>

**Comment by AravindNSS** [comment]
Hi, I was running a testing scan and was using this repo for that https://github.com/tcole3/XSLT-Examples 

Version:  `Sonar-XSL-Plugin: v1.0.0-RC1, Java Version: Java 11.0.17 Eclipse Adoptium (64-bit), OS: Windows Server 2022 and Sonarqube CE: 9.9 (build 65466)`

I got the same error:

`ERROR: Error during SonarScanner execution
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.reset(Unknown Source)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.reset(Unknown Source)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.init(Unknown Source)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(Unknown Source)
        at java.xml/com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(Unknown Source)
        at java.xml/com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(Unknown Source)
        at org.sonar.plugins.xml.highlighting.XMLHighlighting.highlightXML(XMLHighlighting.java:87)
        at org.sonar.plugins.xml.highlighting.XMLHighlighting.<init>(XMLHighlighting.java:71)
        at org.sonar.plugins.xml.highlighting.XMLHighlighting.<init>(XMLHighlighting.java:50)
        at org.sonarxsl.schematron.SchematronSensor.execute(SchematronSensor.java:103)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
        at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:403)
        at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:399)
        at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:368)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
        at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
        at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
        at org.sonarsource.scanner.cli.Main.main(Main.java:62)
ERROR:
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.`

I removed .xsl from XML file suffixes in Sonarqube's general settings since it threw a different error.

Any suggestions on what this issue could be, are much appreciated.

Thanks!

**Comment by jimetevenard** [comment]
I reproduced.  
It's not related to your project, I'm able to reproduce with other sources too.

I'll investigate this afternoon

**Comment by AravindNSS** [comment]
Thanks for looking into this!

**Comment by jimetevenard** [comment]
Fix on [branch `version-update`](https://github.com/sonar-xsl/Sonar-XSL-Plugin/compare/master...version-update) seems to fix.

Next steps :

- [x] Quick local test : **OK** (Sonar : Community 9.9 (build 65466) / sonar-scanner-4.8.0.2856-macosx)
- [ ] Deeper test on several 8.x and 9.x SonarQube versions
- [ ] Ship release

I'll try to do this on Saturday
