### ISSUE TITLE
Error in logs during the build

### ISSUE THREAD

**Issue by jimetevenard** [sonar-xsl/Sonar-XSL-Plugin#7]
- Un-catched error running the Unit-test [TestLanguageDeclaration](https://github.com/sonar-xsl/Sonar-XSL-Plugin/blob/master/sonar-xsl-plugin/src/test/java/org/sonarxsl/plugin/test/TestLanguageDeclaration.java). The following error is outputed to stderr, whithout breaking the build
- ~~(by consequence ?) The plugin do not seems to be recognized by Sonarqube 7.9.2~~

````
Error 
  SXXP0003: Error reported by XML parser: Premature end of file.
Error 
  Error reported by XML parser processing
  jar:file:/root/PRAGUE/SONAR-XSL/Sonar-XSL-Plugin/sonar-schematron-reactor/target/sonar-schematron-reactor-1.0.0-SNAPSHOT.jar!/schematron-code/: Premature end of file.
````

**Comment by jimetevenard** [comment]
:+1:  **This does not prevent the plugin from working** (I simply miscopied the jar when I wrote this Issue)

Still, there should not be any parsing errors.  
_Full stacktrace below_ : 

````
ERROR Error reported by XML parser
; Line#: -1; Column#: -1
net.sf.saxon.trans.XPathException: Error reported by XML parser
	at net.sf.saxon.lib.StandardErrorHandler.reportError(StandardErrorHandler.java:101)
	at net.sf.saxon.lib.StandardErrorHandler.fatalError(StandardErrorHandler.java:85)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:434)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.functions.DocumentFn.makeDoc(DocumentFn.java:331)
	at net.sf.saxon.functions.DocumentFn$DocumentMappingFunction.mapItem(DocumentFn.java:152)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:112)
	at net.sf.saxon.om.SequenceIterator.forEachOrFail(SequenceIterator.java:127)
	at net.sf.saxon.expr.sort.DocumentOrderIterator.<init>(DocumentOrderIterator.java:47)
	at net.sf.saxon.functions.DocumentFn.call(DocumentFn.java:123)
	at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:532)
	at net.sf.saxon.expr.SlashExpression.iterate(SlashExpression.java:920)
	at net.sf.saxon.expr.SlashExpression.iterate(SlashExpression.java:915)
	at net.sf.saxon.expr.sort.DocumentSorter.iterate(DocumentSorter.java:256)
	at net.sf.saxon.expr.AdjacentTextNodeMerger.iterate(AdjacentTextNodeMerger.java:229)
	at net.sf.saxon.expr.Atomizer.iterate(Atomizer.java:331)
	at net.sf.saxon.expr.AtomicSequenceConverter.iterate(AtomicSequenceConverter.java:297)
	at net.sf.saxon.expr.parser.Evaluator$7.evaluate(Evaluator.java:239)
	at net.sf.saxon.expr.SystemFunctionCall.evaluateArguments(SystemFunctionCall.java:446)
	at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:530)
	at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:846)
	at net.sf.saxon.expr.Expression.evaluateAsString(Expression.java:911)
	at net.sf.saxon.expr.instruct.SimpleNodeConstructor.processLeavingTail(SimpleNodeConstructor.java:218)
	at net.sf.saxon.expr.instruct.ValueOf.processLeavingTail(ValueOf.java:290)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:721)
	at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:893)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
	at net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:252)
	at net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353)
	at net.sf.saxon.expr.parser.ExpressionTool.getIteratorFromProcessMethod(ExpressionTool.java:771)
	at net.sf.saxon.expr.instruct.Instruction.iterate(Instruction.java:360)
	at net.sf.saxon.expr.instruct.BlockIterator.next(BlockIterator.java:49)
	at net.sf.saxon.expr.instruct.Message.processLeavingTail(Message.java:225)
	at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:893)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:349)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:487)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:297)
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:254)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:349)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:487)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:297)
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:254)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
	at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:893)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:721)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:349)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:487)
	at net.sf.saxon.expr.instruct.ApplyTemplates$ApplyTemplatesPackage.processLeavingTail(ApplyTemplates.java:554)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:299)
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:254)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:349)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:487)
	at net.sf.saxon.expr.instruct.ApplyTemplates$ApplyTemplatesPackage.processLeavingTail(ApplyTemplates.java:554)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:417)
	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:677)
	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:335)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:327)
	at org.sonarxsl.helpers.SaxonHolder.runXslt(SaxonHolder.java:88)
	at org.sonarxsl.helpers.SaxonHolder.runXslt(SaxonHolder.java:94)
	at org.sonarxsl.schematron.SchematronReader.load(SchematronReader.java:100)
	at org.sonarxsl.schematron.SchematronLanguageDeclaration.declare(SchematronLanguageDeclaration.java:89)
	at org.sonalxsl.plugin.SonarXSLTPlugin.define(SonarXSLTPlugin.java:15)
	at org.sonarxsl.plugin.test.TestLanguageDeclaration.DeclareToFakeContext(TestLanguageDeclaration.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	... 104 more
````

**Comment by jimetevenard** [comment]
Debuging in `net.sf.saxon.functions.DocumentFn.makeDoc(String, String, PackageData, ParseOptions, XPathContext, Location, boolean)` : 

- href is empty
- baseURI is `jar:file:/home/jim/.m2/repository/org/sonarxsl/sonar-schematron-reactor/1.0.0-SNAPSHOT/sonar-schematron-reactor-1.0.0-SNAPSHOT.jar!/schematron-code/iso_schematron_skeleton_for_saxon.xsl`
- XPathContext origin : `CallTemplate#outputLocalizedMessage(number=DocumentInstr(ValueOf("39a")))`


**Exactly the same as issue #5** : The difference is that this errors occurs at the first call to `document("")`.  
The following calls result only in the "Document has been marked not available" warning.

But in this case, Saxon does not provides any location (why ?)

**Comment by jimetevenard** [comment]
Like #5, **This case is very minor** (and strongly linked to Skeleton)
This hase no influence on compilation, only on it's messaging

Through, this shows that errors in compilation are not throwed (Saxon's default listener is an `UnfailingErrorListener`)

So,

- This specific error case can be ignored, but 
- some other errors may occur, that must break the build.
